---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample template to provision an EC2 Instance for private subnet in AZ 2, and NAT gateway.
Mappings:
  AmiMap:
    ServerType01:
      id: ami-00399ec92321828f5

Parameters:
  Scenario1AStackName:
    Description: Name of Scenario 1-A stack
    Type: String
    Default: Scenario-1-A

  Scenario2AStackName:
    Description: Name of Scenario 2-A stack
    Type: String
    Default: Scenario-2-A

  KeyPairName:
    Description: EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: EC2TestCF

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

Resources:
  MyNATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - MyEIP2
        - AllocationId
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario2AStackName}-PublicSubnet2ID"
      Tags:
      - Key: Name
        Value: Scenario-2-NAT-Gateway

  MyEIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      Tags:
      - Key: Name
        Value: Scenario-2-EIP

  myPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario2AStackName}-PrivateRT2ID"
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: MyNATGateway2

  PrivateScenario2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable ssh & icmp
      GroupName: Private-Scenario-2-SG
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 10.100.10.0/24
      - IpProtocol: icmp
        FromPort: 8
        ToPort: -1
        CidrIp: 10.100.10.0/24
        Description: Open Port ALL ICMP - IPv4
      Tags:
      - Key: Name
        Value: Private-Scenario-2-SG
      - Key: Application
        Value:
          Ref: AWS::StackName

  PrivateEC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyPairName
      ImageId:
        Fn::FindInMap:
        - AmiMap
        - ServerType01
        - id
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize: 8
          VolumeType: gp2
      NetworkInterfaces:
      - AssociatePublicIpAddress: false
        DeleteOnTermination: true
        Description: Private EC2 instance network interface
        DeviceIndex: '0'
        SubnetId:
          Fn::ImportValue:
            Fn::Sub: "${Scenario2AStackName}-PrivateSubnet2ID"
        GroupSet:
        - Ref: PrivateScenario2SecurityGroup
      Tags:
      - Key: Name
        Value: Private-Scenario-2-EC2
      - Key: Application
        Value:
          Ref: AWS::StackName

Outputs:
  PrivateSG:
    Description: Scenario 2 Private SG ID
    Value:
      Ref: PrivateScenario2SecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateSGID2"

  PrivateEC2Instance2:
    Description: Scenario 2 Private EC2 ID
    Value:
      Ref: PrivateEC2Instance2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateEC2ID2"
