---
AWSTemplateFormatVersion: 2010-09-09
Description: Create public & private subnets with each route tables
Parameters:
  Scenario1AStackName:
    Description: Name of Scenario 1-A stack
    Type: String
    Default: Scenario-1-A

  AvailabilityZoneName2:
    Description: '2nd Availability Zone '
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-2b

  PublicSubnet2CIDR:
    Description: CIDR of the public subnet in AZ2
    Type: String
    Default: 10.100.10.0/24

  PrivateSubnet2CIDR:
    Description: CIDR of the private subnet in AZ2
    Type: String
    Default: 10.100.11.0/24

Resources:
  myPublicRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"
      Tags:
      - Key: Name
        Value: Scenario-2-Public-RT
      - Key: Application
        Value: AWS::StackName

  myPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"
      Tags:
      - Key: Name
        Value: Scenario-2-Private-RT
      - Key: Application
        Value: AWS::StackName

  myPublicRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: myPublicRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-IGWID"

  myPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"
      AvailabilityZone:
        Ref: AvailabilityZoneName2
      CidrBlock:
        Ref: PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Scenario-2-Public-Subnet
      - Key: Application
        Value: AWS::StackName

  myPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"
      AvailabilityZone:
        Ref: AvailabilityZoneName2
      CidrBlock:
        Ref: PrivateSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Scenario-2-Private-Subnet
      - Key: Application
        Value: AWS::StackName

  myPublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: myPublicSubnet2
      RouteTableId:
        Ref: myPublicRouteTable2

  myPrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: myPrivateSubnet2
      RouteTableId:
        Ref: myPrivateRouteTable2

  myPublicNACL2:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: Name
          Value: Scenario-2-Public-NACL
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"

  myPublicNACLInboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: 
        Ref: myPublicNACL2
      PortRange: 
        From: 0
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100

  myPublicNACLOutboundRule2:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: 
        Ref: myPublicNACL2
      PortRange: 
        From: 0
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100

  publicSubnetNetworkACLAssociation2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: myPublicNACL2
      SubnetId: 
        Ref: myPublicSubnet2

  myPrivateNACL2:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: Name
          Value: Scenario-2-Private-NACL
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${Scenario1AStackName}-VPCID"

  myPrivateNACLInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: 
        Ref: myPrivateNACL2
      PortRange: 
        From: 0
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100

  myPrivateNACLOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: 
        Ref: myPrivateNACL2
      PortRange: 
        From: 0
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100

  privateSubnetNetworkACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: myPrivateNACL2
      SubnetId: 
        Ref: myPrivateSubnet2

Outputs:
  PublicRT2Id:
    Description: Public Route Table 2 ID
    Value:
      Ref: myPublicRouteTable2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PublicRT2ID"

  PrivateRT2Id:
    Description: Private Route Table 2 ID
    Value:
      Ref: myPrivateRouteTable2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateRT2ID"

  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value:
      Ref: myPublicSubnet2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PublicSubnet2ID"

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value:
      Ref: myPrivateSubnet2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateSubnet2ID"

  PublicNACL2Id:
    Description: Public Network ACL 2 ID
    Value:
      Ref: myPublicNACL2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PublicNACL2ID"
        
  PrivateNACL2Id:
    Description: Private Network ACL 2 ID
    Value:
      Ref: myPrivateNACL2
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-PrivateNACL2ID"
